Rename buildpack to devpack, buildpackify to devpacker

diff --git a/devpacker/devpacker b/devpacker/devpacker
--- a/devpacker/devpacker
+++ b/devpacker/devpacker
@@ -1,7 +1,5 @@
 #!/bin/bash
-set -e
-script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-
+script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 osname="$(uname)"
 case $osname in
     Darwin | darwin)
@@ -29,7 +27,16 @@ case $arch in
         ;;
 esac
 
-binary_name="buildpackify-${osname}-${arch}"
+binary_name="devpacker-${osname}-${arch}"
 
-"${script_dir}"/test-generate.sh
-"${script_dir}"/../dist/${binary_name} --mode "devcontainer" finalize "test_image" "${script_dir}/test-project"
+if [ -e "${script_dir}/${binary_name}" ]; then
+    "${script_dir}/${binary_name}" "$@"
+    exit $?
+fi
+
+if [ -e "${script_dir}/dist/${binary_name}" ]; then
+    "${script_dir}/dist/${binary_name}" "$@"
+    exit $?
+fi
+
+echo "Unable to find devpacker binary for ${osname} ${arch}!"
